name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js specified in .nvmrc
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm ci

    - name: Setup Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: 'latest'

    - name: Start server
      run: node server.js &

    - name: Run tests
      run: npm test

    - name: Stop server
      run: pkill -f "node server.js"
